/*
 * Copyright (c) 2025, 2026 Eclipse Foundation and others.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 * // Some portions generated by Co-Pilot
 */
package org.eclipse.cbi.central.plugin;

import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.Parameter;
import org.apache.maven.project.MavenProject;
import org.apache.maven.plugins.annotations.LifecyclePhase;
import org.apache.maven.plugin.MojoFailureException;
import java.util.Map;
import java.util.List;

/**
 * Lists artifacts from a Nexus Repository Manager repository.
 * Can filter by repository and GAV (Group, Artifact, Version) coordinates.
 * Uses the Nexus Repository Manager REST API search endpoint.
 */
@Mojo(name = "nexus-list", defaultPhase = LifecyclePhase.NONE, requiresProject = false)
public class NexusListMojo extends AbstractNexusMojo {
    
    /**
     * If true, displays detailed information for each artifact.
     */
    @Parameter(property = "nexus.showDetails", defaultValue = "false")
    protected boolean showDetails;

    /**
     * Executes the nexus-list goal. Searches and lists artifacts from the Nexus repository.
     */
    @Override
    public void execute() throws MojoFailureException {
        try {
            getLog().info("Starting nexus-list goal");
            
            // Skip execution root check if no project
            if (project != null && !project.isExecutionRoot()) {
                getLog().info("Skipping nexus-list: not execution root");
                return;
            }
            
            initClient();

            for(MavenProject targetProject : resolveTargetProjects()) {
                getLog().info("Processing project: " + targetProject.getId().replace("null", "<empty>"));

                // Determine effective search parameters from project if available
                String effectiveGroup = determineEffectiveGroup(targetProject);
                String effectiveArtifact = determineEffectiveArtifact(targetProject);

                // Log search criteria
                logSearchCriteria(effectiveGroup, effectiveArtifact);
                
                // Perform search
                Map<String, Object> result = client.searchComponents(
                    repository, 
                    effectiveGroup, 
                    effectiveArtifact, 
                    version
                );

                // Process and display results
                displaySearchResults(result);   
            }
        } catch (Exception e) {
            getLog().error("Failed to list Nexus artifacts", e);
            throw new MojoFailureException("Failed to list Nexus artifacts", e);
        }
    }

    /**
     * Determines the effective group parameter.
     * Only uses project groupId if explicitly set via nexus.group parameter
     * or if a valid pom.xml exists in the current directory.
     */
    private String determineEffectiveGroup(MavenProject targetProject) {
        if (group != null && !group.isEmpty()) {
            return group;
        } else if (targetProject != null) {
            return targetProject.getGroupId();
        }
        return null;
    }

    /**
     * Determines the effective artifact parameter.
     * Only uses project artifactId if explicitly set via nexus.artifact parameter
     * or if a valid pom.xml exists in the current directory.
     */
    private String determineEffectiveArtifact(MavenProject targetProject) {
        if (artifact != null && !artifact.isEmpty()) {
            return artifact;
        } else if (targetProject != null) {
            return targetProject.getArtifactId();
        }
        return null;
    }

    /**
     * Logs the search criteria being used.
     */
    private void logSearchCriteria(String effectiveGroup, String effectiveArtifact) {
        StringBuilder criteria = new StringBuilder("Search criteria:");
        if (repository != null && !repository.isEmpty()) {
            criteria.append(" repository=").append(repository);
        } else {
            criteria.append(" repository=(all)");
            getLog().warn("No repository specified (nexus.repository). Search will be performed across all repositories which may be slower and less optimal.");
        }
        if (effectiveGroup != null) {
            criteria.append(", group=").append(effectiveGroup);
        }
        if (effectiveArtifact != null) {
            criteria.append(", artifact=").append(effectiveArtifact);
        }
        if (version != null && !version.isEmpty()) {
            criteria.append(", version=").append(version);
        }
        getLog().info(criteria.toString());
    }

    /**
     * Displays the search results from the Nexus API response.
     */
    private void displaySearchResults(Map<String, Object> result) {
        Object itemsObj = result.get("items");
        if (!(itemsObj instanceof List)) {
            getLog().info("No artifacts found.");
            return;
        }
        
        List<?> items = (List<?>) itemsObj;
        if (items.isEmpty()) {
            getLog().info("No artifacts found.");
            return;
        }
        
        getLog().info("Found " + items.size() + " artifact(s):");
        getLog().info("─────────────────────────────────────────────────────────────");
        
        for (Object itemObj : items) {
            if (itemObj instanceof Map) {
                displayArtifact((Map<?, ?>) itemObj);
            }
        }
        
        // Display continuation token if available
        Object continuationTokenObj = result.get("continuationToken");
        if (continuationTokenObj != null) {
            getLog().info("─────────────────────────────────────────────────────────────");
            getLog().info("Note: More results are available. The search returned a continuation token.");
        }
    }

    /**
     * Displays information about a single artifact.
     */
    protected void displayArtifact(Map<?, ?> item) {
        Object id = item.get("id");
        Object repositoryObj = item.get("repository");
        Object format = item.get("format");
        Object groupObj = item.get("group");
        Object name = item.get("name");
        Object versionObj = item.get("version");
        
        // Build artifact display string
        StringBuilder display = new StringBuilder();
        if (groupObj != null) {
            display.append(groupObj).append(":");
        }
        if (name != null) {
            display.append(name).append(":");
        }
        if (versionObj != null) {
            display.append(versionObj);
        }

        if (id != null) {
            display.append(" (id=").append(id).append(")");
        }
        
        getLog().info("• " + display.toString());
        
        if (showDetails) {
            if (repositoryObj != null) {
                getLog().info("  Repository: " + repositoryObj);
            }
            if (format != null) {
                getLog().info("  Format: " + format);
            }
            if (id != null) {
                getLog().info("  Component ID: " + id);
            }
            
            // Display assets if available
            Object assetsObj = item.get("assets");
            if (assetsObj instanceof List<?> assets && !assets.isEmpty()) {
                getLog().info("  Assets (" + assets.size() + "):");
                for (Object assetObj : assets) {
                    if (assetObj instanceof Map) {
                        displayAsset((Map<?, ?>) assetObj);
                    }
                }
            }
            getLog().info("");
        }
    }

    /**
     * Displays information about a single asset.
     */
    private void displayAsset(Map<?, ?> asset) {
        Object path = asset.get("path");
        Object downloadUrl = asset.get("downloadUrl");
        Object contentType = asset.get("contentType");
        
        if (path != null) {
            getLog().info("    - " + path);
            if (downloadUrl != null) {
                getLog().info("      URL: " + downloadUrl);
            }
            if (contentType != null) {
                getLog().info("      Type: " + contentType);
            }
        }
    }
}
