/*
 * Copyright (c) 2026 Eclipse Foundation and others.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 * // Some portions generated by Co-Pilot
 */
package org.eclipse.cbi.central.plugin;

import java.util.List;
import java.util.Map;

import org.apache.maven.plugin.MojoFailureException;
import org.apache.maven.plugins.annotations.LifecyclePhase;
import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.Parameter;
import org.apache.maven.project.MavenProject;

/**
 * Lists artifacts from a Nexus Repository Manager repository.
 * Can filter by repository and GAV (Group, Artifact, Version) coordinates.
 * Uses the Nexus Repository Manager REST API search and delete endpoints.
 */
@Mojo(name = "nexus-drop", defaultPhase = LifecyclePhase.NONE, requiresProject = false)
public class NexusDropMojo extends NexusListMojo {

    /**
     * The component ID to drop from the Nexus Repository Manager.
     * If unset, will drop based on GAV coordinates.
     */
    @Parameter(property = "nexus.componentId")
    protected String componentId;

    /**
     * If true, only simulate the drop (do not actually drop deployments).
     */
    @Parameter(property = "nexus.dryRun", defaultValue = "false")
    protected boolean dryRun;

    @Override
    public void execute() throws MojoFailureException {
        try {
            getLog().info("Starting nexus-drop goal");

            // Skip execution root check if no project
            if (project != null && !project.isExecutionRoot()) {
                getLog().info("Skipping nexus-drop: not execution root");
                return;
            }

            initClient();

            // If componentId is provided, drop that directly
            if (componentId != null && !componentId.isEmpty()) {
                getLog().info("Dropping component with ID: " + componentId);
                if (dryRun) {
                    getLog().info("Dry run enabled: no components were dropped");
                } else {
                    logDeleteResponse(client.deleteComponent(componentId));
                }
                return;
            }

            // Otherwise, drop based on GAV search, for each target project
            for (MavenProject targetProject : resolveTargetProjects()) {
                getLog().info("Processing project: " + targetProject.getId().replace("null", "<empty>"));

                // Perform search
                Map<String, Object> result = client.searchComponents(
                        repository,
                        targetProject.getGroupId(),
                        targetProject.getArtifactId(),
                        targetProject.getVersion());

                // Process and display found artifacts
                Object itemsObj = result.get("items");
                if (!(itemsObj instanceof List)) {
                    getLog().info("No artifacts found.");
                    continue;
                }

                List<?> items = (List<?>) itemsObj;
                if (items.isEmpty()) {
                    getLog().info("No artifacts found.");
                    continue;
                }

                getLog().info("Found " + items.size() + " artifact(s):");
                getLog().info("─────────────────────────────────────────────────────────────");

                // Iterate and drop each found artifact
                for (Object itemObj : items) {
                    if (itemObj instanceof Map) {
                        Map<?, ?> item = (Map<?, ?>) itemObj;
                        String id = (String) item.get("id");

                        displayArtifact(item);

                        getLog().info("Dropping component with ID: " + id);

                        if (dryRun) {
                            getLog().info("Dry run enabled: no components were dropped");
                        } else {
                            logDeleteResponse(client.deleteComponent(id));
                        }
                    }
                }
            }
        } catch (Exception e) {
            getLog().error("Failed to drop Nexus artifacts", e);
            throw new MojoFailureException("Failed to drop Nexus artifacts", e);
        }
    }

    /**
     * Logs the delete response.
     */
    private void logDeleteResponse(Map<String, Object> result) {
        // TODO - implement detailed logging of delete response once API response
        // structure is known
        // for example is a json response with details returned?
        getLog().info("Delete response: " + result);
    }
}