/*
 * Copyright (c) 2025 Eclipse Foundation and others.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * // Some portions generated by Co-Pilot
 */

package org.eclipse.cbi.central.plugin;

import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.Parameter;
import org.apache.maven.plugins.annotations.LifecyclePhase;
import org.apache.maven.plugin.MojoFailureException;
import org.eclipse.cbi.central.DeploymentConstants;
import java.util.Map;

@Mojo(name = "rc-drop", defaultPhase = LifecyclePhase.NONE)
public class RcDropMojo extends AbstractCentralMojo {

    /**
     * If true, only simulate the drop (do not actually drop deployments).
     */
    @Parameter(property = "central.dryRun", defaultValue = "false")
    protected boolean dryRun;

    /**
     * The deployment ID to drop. Otherwise, the latest deployment will be dropped.
     */
    @Parameter(property = "central.deploymentId")
    protected String deploymentId;

    /**
     * Executes the rc-drop goal. Drops the deployment with the specified
     * deploymentId.
     */
    @Override
    public void execute() throws MojoFailureException {
        try {
            getLog().info("Starting rc-drop goal");
            if (!project.isExecutionRoot()) {
                getLog().info("Skipping rc-drop: not execution root");
                return;
            }
            initClient();
            if (removeAll) {
                dropAllDeployments(removeFailedOnly, dryRun);
            } else if (deploymentId != null && !deploymentId.isEmpty()) {
                if (removeFailedOnly) {
                    Map<String, Object> status = client.getDeploymentStatus(deploymentId);
                    Object state = status.get(DeploymentConstants.DEPLOYMENT_STATE);
                    if (!DeploymentConstants.FAILED_STATE.equals(String.valueOf(state))) {
                        getLog().info(
                                "Deployment " + deploymentId + " is not in " + DeploymentConstants.FAILED_STATE
                                        + " state. Skipping drop.");
                        return;
                    }
                }
                if (dryRun) {
                    getLog().info("[DRY RUN] Would drop deployment " + deploymentId);
                } else {
                    Map<String, Object> result = client.dropDeployment(deploymentId);
                    getLog().info("Dropped deployment " + deploymentId + " result: " + result);
                }
            } else {
                // Drop the latest deployment if neither removeAll nor deploymentId is set
                String namespace = project.getGroupId();
                Map<String, Object> deploymentsResult = client.listDeployments(namespace, 0, 1, "createTimestamp",
                        "desc");
                Object deploymentsObj = deploymentsResult.get(DeploymentConstants.DEPLOYMENTS);
                if (deploymentsObj instanceof java.util.List<?> deployments && !deployments.isEmpty()) {
                    Map<?, ?> latestDep = (Map<?, ?>) deployments.get(0);
                    String latestId = String.valueOf(latestDep.get(DeploymentConstants.DEPLOYMENT_ID));
                    String state = String.valueOf(latestDep.get(DeploymentConstants.DEPLOYMENT_STATE));
                    if (removeFailedOnly && !DeploymentConstants.FAILED_STATE.equals(state)) {
                        getLog().info("Latest deployment " + latestId + " is not in FAILED state. Skipping drop.");
                        return;
                    }
                    if (dryRun) {
                        getLog().info("[DRY RUN] Would drop latest deployment " + latestId + " (state: " + state + ")");
                    } else {
                        Map<String, Object> result = client.dropDeployment(latestId);
                        getLog().info(
                                "Dropped latest deployment " + latestId + " (state: " + state + ") result: " + result);
                    }
                } else {
                    getLog().info("No deployments found to drop.");
                }
            }
        } catch (Exception e) {
            getLog().error("Failed to drop deployment", e);
            throw new MojoFailureException("Failed to drop deployment", e);
        }
    }

    /**
     * Drops all deployments in the namespace. If onlyFailed is true, only drops
     * deployments in FAILED state.
     * If dryRun is true, only simulates the drop.
     */
    private void dropAllDeployments(boolean onlyFailed, boolean dryRun) throws MojoFailureException {
        String namespace = project.getGroupId();
        try {
            Map<String, Object> deploymentsResult = client.listDeployments(namespace, 0, 500, "createTimestamp",
                    "desc");
            Object deploymentsObj = deploymentsResult.get(DeploymentConstants.DEPLOYMENTS);
            if (deploymentsObj instanceof java.util.List<?> deployments) {
                for (Object depObj : deployments) {
                    if (depObj instanceof Map<?, ?> dep &&
                            (!onlyFailed || DeploymentConstants.FAILED_STATE
                                    .equals(String.valueOf(dep.get(DeploymentConstants.DEPLOYMENT_STATE))))) {
                        dropSingleDeployment(dep, dryRun);

                    }
                }
            } else {
                getLog().info("No deployments found to drop.");
            }
        } catch (Exception e) {
            getLog().error("Error dropping deployments", e);
            throw new MojoFailureException("Error dropping deployments", e);
        }
    }

    /**
     * Drops a single deployment and logs the result or any error. If dryRun is
     * true, only simulates the drop.
     */
    private void dropSingleDeployment(Map<?, ?> dep, boolean dryRun) throws MojoFailureException {
        String id = String.valueOf(dep.get(DeploymentConstants.DEPLOYMENT_ID));
        String state = String.valueOf(dep.get(DeploymentConstants.DEPLOYMENT_STATE));
        if (dryRun) {
            getLog().info("[DRY RUN] Would drop deployment " + id + " (state: " + state + ")");
            return;
        }
        try {
            Map<String, Object> result = client.dropDeployment(id);
            getLog().info("Dropped deployment " + id + " (state: " + state + ") result: " + result);
        } catch (Exception e) {
            getLog().error("Failed to drop deployment " + id + " (state: " + state + ")", e);
            throw new MojoFailureException("Failed to drop deployment " + id + " (state: " + state + ")", e);
        }
    }
}
