/*
 * Copyright (c) 2025 Eclipse Foundation and others.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0 which is available at
 * https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * // Some portions generated by Co-Pilot
 */
package org.eclipse.cbi.central.plugin;

import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.Parameter;
import org.apache.maven.plugins.annotations.Component;
import org.apache.maven.plugins.annotations.LifecyclePhase;
import org.apache.maven.plugin.MojoFailureException;

import java.io.File;
import java.util.List;

import org.apache.maven.project.MavenProject;

import org.eclipse.aether.RepositorySystem;

/**
 * Maven goal for complete artifact synchronization workflow to Maven Central.
 * 
 * The rc-sync goal orchestrates the complete process of downloading artifacts
 * from
 * remote repositories, creating deployment bundles, uploading to Maven Central
 * staging,
 * publishing artifacts, and cleaning up staging deployments.
 * 
 * This goal chains together multiple RC goals (rc-download, rc-bundle,
 * rc-upload,
 * rc-publish, rc-drop) to provide an end-to-end synchronization workflow
 * suitable
 * for complex deployment scenarios.
 * 
 * @since 1.0.0
 */
@Mojo(name = "rc-sync", defaultPhase = LifecyclePhase.NONE, requiresProject = false)
public class RcSyncMojo extends AbstractStagingMojo {

    /**
     * Maven Artifact Resolver system for downloading artifacts.
     * Injected by Maven and passed to RcDownloadMojo when needed.
     */
    @Component
    protected RepositorySystem repositorySystem;

    /**
     * If true, skip the bundle creation phase entirely and use existing bundle
     * file.
     */
    @Parameter(property = "central.skipBundle", defaultValue = "false")
    protected boolean skipBundle;

    /**
     * If true, automatically publish artifacts after successful upload.
     */
    @Parameter(property = "central.syncAutoPublish", defaultValue = "false")
    protected boolean syncAutoPublish;

    /**
     * If true, automatically drop all standby staging deployments after successful
     * publish.
     */
    @Parameter(property = "central.syncDropAfterPublish", defaultValue = "true")
    protected boolean syncDropAfterPublish;

    // ================================================================================================
    // MAIN EXECUTION METHODS
    // ================================================================================================

    /**
     * Main execution method for the rc-sync Maven goal.
     * 
     * Coordinates the complete synchronization process by orchestrating multiple
     * RC goals: download, bundle creation, upload to Central, optional publishing,
     * and cleanup.
     * 
     * The workflow follows these phases:
     * 1. Configuration validation and GAV resolution
     * 2. Download phase (via rc-download, if not skipped)
     * 3. Bundle creation phase (via rc-bundle, if not skipped)
     * 4. Upload phase (via rc-upload)
     * 5. Optional publish phase (via rc-publish, if syncAutoPublish=true)
     * 6. Optional cleanup phase (via rc-drop, if syncDropAfterPublish=true)
     * 
     * @throws MojoFailureException if any step in the synchronization process fails
     */
    @Override
    public void execute() throws MojoFailureException {
        getLog().info("Starting rc-sync goal");
        if (!project.isExecutionRoot()) {
            getLog().info("Skipping rc-sync: not execution root");
            return;
        }
        String[] gav = resolveEffectiveGav();
        showConfig(gav);

        if (this.dryRun) {
            getLog().info("");
            getLog().info("=== DRY-RUN MODE ACTIVATED ===");
            getLog().info("No actual operations will be performed - showing execution plan");
            getLog().info("");
        }

        if (this.skipBundle) {
            getLog().info("Skipping bundle creation: central.skipBundle=true");
            if (syncBundleFile == null || !syncBundleFile.exists()) {
                throw new MojoFailureException("Bundle file does not exist: " + syncBundleFile +
                        ". Cannot skip bundle creation without existing bundle file.");
            }
            getLog().info("Using existing bundle file: " + syncBundleFile.getAbsolutePath());
        } else {
            buildBundleUsingbundleMojo();
        }

        if (this.dryRun) {
            getLog().info("");
            getLog().info("=== DRY-RUN SUMMARY ===");
            getLog().info("All operations completed successfully in dry-run mode.");
            getLog().info("To execute these operations for real, run the same command without -Dcentral.dryRun=true");
            getLog().info("");
            return;
        }
        performUpload();
        boolean published = this.syncAutoPublish && runPublish(gav);
        if (published && this.syncDropAfterPublish) {
            runDropStandby();
        }
    }

    // ================================================================================================
    // BUNDLE BUILDING METHODS
    // ================================================================================================

    /**
     * Builds a bundle by delegating to the rc-bundle goal for complete artifact
     * processing.
     * 
     * This method creates and configures an RcBundleMojo instance, maps all
     * necessary
     * configuration parameters, and delegates the bundle creation process.
     * 
     * @return The bundle file created from processed artifacts (null in dry-run
     *         mode)
     * @throws MojoFailureException if the bundle creation fails
     */
    private void buildBundleUsingbundleMojo() throws MojoFailureException {
        // Create and configure the bundle mojo
        RcBundleMojo bundleMojo = new RcBundleMojo();

        // Map configuration using organized helper method
        mapConfigurationToBundleMojo(bundleMojo);

        // Delegate the bundle building to the bundle mojo
        bundleMojo.execute();
    }

    /**
     * Maps all configuration from this RcSyncMojo to the target RcBundleMojo.
     * This centralized mapping method makes it easy to maintain and ensures
     * all properties are copied consistently.
     * 
     * @param bundleMojo The target rc-bundle mojo to configure
     */
    private void mapConfigurationToBundleMojo(RcBundleMojo bundleMojo) {
        // AbstractCentralMojo inherited properties
        bundleMojo.serverId = this.serverId;
        bundleMojo.centralApiUrl = this.centralApiUrl;
        bundleMojo.project = this.project;
        bundleMojo.settings = this.settings;

        // AbstractStagingMojo inherited properties - directly accessible
        bundleMojo.serverSyncId = this.serverSyncId;
        bundleMojo.repositoryUrl = this.repositoryUrl;
        bundleMojo.repositoryLayout = this.repositoryLayout;
        bundleMojo.namespace = this.namespace;
        bundleMojo.name = this.name;
        bundleMojo.version = this.version;
        bundleMojo.syncStagingDirName = this.syncStagingDirName;
        bundleMojo.syncStagingDir = this.syncStagingDir;
        bundleMojo.syncBundleFile = this.syncBundleFile;
        bundleMojo.dryRun = this.dryRun;
        bundleMojo.skipDownload = this.skipDownload;
        bundleMojo.generateChecksums = this.generateChecksums;
        bundleMojo.forceGenerateChecksums = this.forceGenerateChecksums;
        bundleMojo.generateChecksums256 = this.generateChecksums256;
        bundleMojo.generateChecksums512 = this.generateChecksums512;
        bundleMojo.signArtifacts = this.signArtifacts;
        bundleMojo.forceSignArtifacts = this.forceSignArtifacts;
        bundleMojo.p2Metadata = this.p2Metadata;
        bundleMojo.downloadSignatures = this.downloadSignatures;
        bundleMojo.downloadChecksums = this.downloadChecksums;
        bundleMojo.downloadChecksums256 = this.downloadChecksums256;
        bundleMojo.downloadChecksums512 = this.downloadChecksums512;
        bundleMojo.failOnMissingSourcesJavadoc = this.failOnMissingSourcesJavadoc;
        bundleMojo.failOnMissingSignatureFile = this.failOnMissingSignatureFile;
        bundleMojo.failOnMissingChecksum = this.failOnMissingChecksum;
        bundleMojo.showMavenGoalOutput = this.showMavenGoalOutput;
        bundleMojo.reactorProjects = this.reactorProjects;
        bundleMojo.session = this.session;
        bundleMojo.invoker = this.invoker;
        bundleMojo.mojoExecution = this.mojoExecution;
        bundleMojo.repositorySystem = this.repositorySystem;

        // RcBundleMojo specific - force ZIP creation for sync operation
        bundleMojo.zipArtifacts = true;

        if (this.project != null) {
            bundleMojo.project = this.project;
        }
    }

    // ================================================================================================
    // UTILITY METHODS
    // ================================================================================================

    /**
     * Displays the current configuration and GAV coordinates to be synchronized.
     * 
     * @param gav The GAV (Group:Artifact:Version) array to display
     */
    private void showConfig(String[] gav) {
        getLog().info("GAV to sync: " + String.join(":", gav));
        getLog().info(
                "Config: \n" +
                        "  ============== Central Configuration ===============\n" +
                        "         central.bearerCreate=" + this.bearerCreate + "\n" +
                        "  ============== Remote Repository Configuration ===============\n" +
                        "         central.serverSyncId=" + this.serverSyncId + "\n" +
                        "         central.repositoryUrl=" + (this.repositoryUrl != null ? this.repositoryUrl : "null")
                        + "\n" +
                        "         central.repositoryLayout=" + this.repositoryLayout + "\n" +
                        "  =============== GAV Configuration ===============\n" +
                        "         central.namespace=" + (this.namespace != null ? this.namespace : "default") + "\n" +
                        "         central.name=" + (this.name != null ? this.name : "default") + "\n" +
                        "         central.version=" + (this.version != null ? this.version : "default") + "\n" +
                        "  =============== File and Directory Configuration ===============\n" +
                        "         central.syncStagingDir="
                        + (this.syncStagingDir != null ? this.syncStagingDir : "default") + "\n" +
                        "         central.syncBundleFile="
                        + (this.syncBundleFile != null ? this.syncBundleFile.getAbsolutePath() : "default") + "\n" +
                        "         central.bundleName="
                        + (this.bundleName != null ? this.bundleName : "artifact filename without extension") + "\n" +
                        "  =============== Execution Mode Configuration ===============\n" +
                        "         central.dryRun=" + this.dryRun + "\n" +
                        "         central.skipBundle=" + this.skipBundle + "\n" +
                        "         central.skipDownload=" + this.skipDownload + "\n" +
                        "         central.automaticPublishing=" + this.automaticPublishing + "\n" +
                        "         central.syncAutoPublish=" + this.syncAutoPublish + "\n" +
                        "         central.syncDropAfterPublish=" + this.syncDropAfterPublish + "\n" +
                        "  =============== Artifact Processing Configuration ===============\n" +
                        "         central.generateChecksums=" + this.generateChecksums + "\n" +
                        "         central.forceGenerateChecksums=" + this.forceGenerateChecksums + "\n" +
                        "         central.generateChecksums256=" + this.generateChecksums256 + "\n" +
                        "         central.generateChecksums512=" + this.generateChecksums512 + "\n" +
                        "         central.signArtifacts=" + this.signArtifacts + "\n" +
                        "         central.forceSignArtifacts=" + this.forceSignArtifacts + "\n" +
                        "         central.p2Metadata=" + this.p2Metadata + "\n" +
                        "  =============== Drop Configuration ===============\n" +
                        "         central.removeAll=" + this.removeAll + "\n" +
                        "         central.removeFailedOnly=" + this.removeFailedOnly + "\n" +
                        "  =============== Central API Configuration ===============\n" +
                        "         central.serverId=" + (this.serverId != null ? this.serverId : "default") + "\n" +
                        "         central.centralApiUrl="
                        + (this.centralApiUrl != null ? this.centralApiUrl : "default"));
    }

    /**
     * Uploads the bundle to Maven Central using the rc-upload goal.
     * 
     * This method creates and configures an RcUploadMojo instance with the
     * necessary
     * parameters for bundle upload, including authentication and API configuration.
     * 
     * @throws MojoFailureException if upload fails due to authentication, network,
     *                              or API issues
     */
    private void performUpload() throws MojoFailureException {
        RcUploadMojo uploadMojo = new RcUploadMojo();
        uploadMojo.syncBundleFile = syncBundleFile;
        uploadMojo.bundleName = bundleName;
        // Use the dedicated upload automaticPublishing flag
        uploadMojo.automaticPublishing = this.automaticPublishing;
        uploadMojo.project = this.project;
        uploadMojo.settings = this.settings;
        uploadMojo.serverId = this.serverId;
        uploadMojo.centralApiUrl = this.centralApiUrl;
        try {
            uploadMojo.execute();
            getLog().info("Upload via RcUploadMojo completed.");
        } catch (Exception e) {
            getLog().error("Error during bundle upload", e);
            throw new MojoFailureException("Bundle upload error", e);
        }
    }

    /**
     * Publishes the staged artifacts using the rc-publish goal.
     * 
     * This method triggers the publication of all artifacts currently staged in
     * Maven Central
     * for the configured namespace. Publication makes artifacts publicly available.
     * 
     * @param gav The GAV coordinates being published (used for logging)
     * @return true if publication succeeded, false if publication failed
     */
    private boolean runPublish(String[] gav) {
        getLog().info("Publishing module: " + String.join(":", gav));

        boolean allOk = true;

        RcPublishMojo publishMojo = new RcPublishMojo();
        publishMojo.settings = this.settings;
        publishMojo.serverId = this.serverId;
        publishMojo.centralApiUrl = this.centralApiUrl;
        try {
            publishMojo.execute();
            getLog().info("Publication OK for module " + String.join(":", gav));
        } catch (Exception e) {
            allOk = false;
            getLog().error("Error during publication of module " + String.join(":", gav), e);
        }
        return allOk;
    }

    /**
     * Drops (removes) standby staging deployments using the rc-drop goal.
     * 
     * This cleanup method removes staging deployments that are no longer needed,
     * typically called after successful publication. Can be configured to remove
     * all deployments or only failed ones.
     */
    private void runDropStandby() {
        RcDropMojo dropMojo = new RcDropMojo();
        dropMojo.project = this.project;
        dropMojo.settings = this.settings;
        dropMojo.serverId = this.serverId;
        dropMojo.centralApiUrl = this.centralApiUrl;
        dropMojo.removeAll = this.removeAll;
        dropMojo.removeFailedOnly = this.removeFailedOnly;
        dropMojo.dryRun = this.dryRun;
        try {
            dropMojo.execute();
            getLog().info("Cleanup via RcDropMojo completed.");
        } catch (Exception e) {
            getLog().error("Error during standby deployments drop", e);
        }
    }
}